### ISSUE TITLE
Gaussian noise generator in nip2 creates image artifacts

### ISSUE THREAD

**Issue by mhirsch** [libvips/nip2#103]
The Gaussian noise generator in nip2 seems to produce structured output -- I see bands in the image that should average to gray. Here's an example running `Pattern_images_item.Noise_item.Gaussian_item.action` with Mean 128 and Deviation 25.
![nip2-gaussian-noise](https://user-images.githubusercontent.com/424951/152207342-e0a52ad0-e2bc-4a4c-9c40-7f067374729f.png)

For comparison, here's an example using the Magick toolkit for nip2, `add Noise` with type set to Gaussian, and adding it to uniform 128 value image:
![im-gaussian-noise](https://user-images.githubusercontent.com/424951/152206799-daf57941-4204-4a01-8dfc-3bd3b86b247f.png)

Do you have any suggestions for getting the nip2 output to look close to ImageMagick?

Thanks!

**Comment by jcupitt** [comment]
Hi Matt, ouch, looks like the libvips random number generator should be improved. I've opened an issue: https://github.com/libvips/libvips/issues/2642

**Comment by jcupitt** [comment]
OK, fixed, I hope. Thanks for pointing this out.

**Comment by mhirsch** [comment]
Curious - will this fix make it's way back to nip2 any time soon, since it uses vips 7? Thank you again for taking the time to solve this so quickly!

**Comment by jcupitt** [comment]
Yes, the vips7 API is just a thin skin over vips8, so all vips8 fixes get into nip2.
