### ISSUE TITLE
Fedora 38 Package is Missing PNG Support

### ISSUE THREAD

**Issue by mhirsch** [libvips/nip2#108]
I know you're not the package manager for Fedora, but I'm hoping you can point me in the right direction to track down missing PNG support in the Fedora 38 nip2 package.

In the version of nip2 packaged in Fedora 37 PNG was an option in the open and save dialogs. In the Fedora 38 version of the package, they call `nip2-8.7.1-14.fc38.x86_64`, the PNG option is missing, and trying to open a PNG results in an "unsupported image type" dialog.

I don't see any obvious `configure` flags for toggling libpng, or `#define`s in the code, or anything in their RPM `.spec` file that would control this.

Thanks!

**Comment by jcupitt** [comment]
Hi @mhirsch,

It looks like fedora have built libvips against libspng, not libpng:

https://packages.fedoraproject.org/pkgs/vips/vips/fedora-38.html

Our libspng loader doesn't have a vips7 interface, and that's what nip2 uses unfortunately :(

I'll make a libvips issue to add a vips7 interface for spng load. In the meantime I think your only fix will be to build your own libvips :(

**Comment by jcupitt** [comment]
libvips issue https://github.com/libvips/libvips/issues/3466

**Comment by jcupitt** [comment]
Ah in fact there was a vip7 wrapper, but it was not being registered when building with libspng. I've made a PR and this fix should be in 8.14.3.

Thanks for reporting this!

**Comment by mhirsch** [comment]
Hi @jcupitt -- I have been installing nip2 via snap while waiting for fedora to update their package. 

I installed it yesterday and noticed that in this instance the version of nip2 from snap was also missing the option to open PNG files. Here's my version info:

```
$ snap info vips-nip2 
name:      vips-nip2
summary:   An image-processing spreadsheet.
publisher: John Cupitt (vips)
store-url: https://snapcraft.io/vips-nip2
contact:   jcupitt@gmail.com
license:   unset
description: |
  nip2 is half-way between a spreadsheet and a paint program.
  It's terrible for retouching photographs, but very handy for automating image
  processing tasks.
  
  It can process multi-gigabyte images efficiently. It has good support for
  scientific image formats. It's much faster and more flexible than tools like
  ImageJ.
  
  This snap is git master nip2 built with git master libvips.
commands:
  - vips-nip2.nip2
snap-id:      wuZC6ITitKbV3uZoAm7pOPfJnz45IjdX
tracking:     latest/edge
refresh-date: yesterday at 11:51 EDT
channels:
  latest/stable:    –                             
  latest/candidate: –                             
  latest/beta:      –                             
  latest/edge:      master 2023-02-18 (1676) 92MB -
installed:          master            (1676) 92MB -
```

Is there any chance that this is related to the change you made for the above libspng fix? I have the same `snap-id: wuZC6ITitKbV3uZoAm7pOPfJnz45IjdX` installed on two different computers and one of them has the option to open PNGs and the other does not! I have uninstalled the Fedora nip2 package on both.

**Comment by jcupitt** [comment]
That's curious. I made the snap years ago as an experiment, but I've not been maintaining it. 

Perhaps someone else has tried to update it for more recent libvipses, but accidentally broken PNG load?
