### ISSUE TITLE
vips_call "copy" does not copy despite (seemingly) calculating without error

### ISSUE THREAD

**Issue by larsmaxfield** [libvips/nip2#109]
I'm trying to convert the file type of an image by calling copy with vips_call. 

The following call appears to calculate without error, though the actual copying does not occur:
```
vips_call "copy" [A1.value, "C:\output\fred.jpg[Q=100]"]
```
I've tested this with various image types as input and output with no difference.

Other calls _do_ work on the images I am using as input. For example, dzsave is successful with:
```
vips_call "dzsave" [A1.value, "C:\output\fred"] []
```

This is on Windows 10 with the nip2-8.7.0 binary.

Is there perhaps something wrong with my call?

**Comment by jcupitt** [comment]
Hey @larsmaxfield,

`copy` makes a copy of a `VipsImage*`, it doesn't write to a file. You'd use it like:

```
A2 = Image (vips_call "copy" [A1.value])
```

If you want to write to a file, you can call the savers directly, eg.:

```
vips_call "jpegsave" [A1.value, "C:\output\fred.jpg"] ["Q" => 100]
```

Are you trying to automatically save the result of a computation? I would use nip2 batch mode, it's designed for things like this and works pretty well. There's a chapter in the docs about it.

**Comment by larsmaxfield** [comment]
Thanks @jcupitt for explaining that.

Indeed with that call I was seeking how to write to a file as a way to convert the file type of that image. 

More broadly I'm seeking an installable GUI-based program for non-programmers to run operations on images on their own (Windows) machines. Things like converting the file type of images, batch cropping, and generating pyramid .tiff's.

My thought is that nip2 could be our solution, perhaps with the help of fill-in-the-blank workspaces which I create for them to (re)use as needed. The batch processing of nip2 (as you suggest) will be useful for me, but it may be a stretch for our users. 

Do you have any thoughts or suggestions on this? I've considered making a simple GUI myself for this purpose, though in Python with pyvips/PyQt/PyInstaller.

**Comment by jcupitt** [comment]
vipsdisp can convert file types:

https://github.com/jcupitt/vipsdisp

But it's not scriptable and has no cropping or batch :( It's going to be the image display window for nip4, if I ever find the time to work on it.

I guess you saw the View / No Edits mode in nip2? It makes it a little less intimidating.

You're right, a little custom GUI using PyQt might be the best thing.
