### ISSUE TITLE
nip2 lockup on using someting like "27//3".

### ISSUE THREAD

**Issue by MvGulik** [libvips/nip2#111]
"3**3"=27 ... so I tried "27//3" just to see what that would do.
Nip2 did not like that at all, so it stopped responding, and had to be forcibly euthanized.

Linked to VIPS: 8.9.1-Sun Feb 23 08:51:26 UTC 2020
Built against VIPS: 8.6.5-Thu Jul 26 22:22:33 UTC 2018
$PACKAGE: nip2
$VERSION: 8.7.0
-- On: Linux Mint 20.3

On a side note: I have been eyeballing the "installing from source" notes ... but as a non builder its only raises questions instead of being of any use. :-(

(_With Snapcraft & Flatpak taking over the updating scene. The local package manager seems to become more and more a old and outdated apps collection than anything else. AppImage on the other hand I still trust_.)

**Comment by jcupitt** [comment]
Wow, you're right, it sends the parser into a tailspin. I'll have a look, thanks for the report.

**Comment by jcupitt** [comment]
I fixed it and credited you in the changelog. Thanks!
