### ISSUE TITLE
?: Saving/export histogram to similar image as its displayed by Nip2.

### ISSUE THREAD

**Issue by MvGulik** [libvips/nip2#117]
![Screenshot (2024-04-24 11:07:40)A](https://github.com/libvips/nip2/assets/666868/7e7d48b1-dd44-4b29-aca5-ec91a24087e1)
Created this simple height-map scanning ws (_yellow text not included_). But ... its there a relative simple way to turn (or save) that histogram into an image as its displayed by nip2 ?

I figure I could use python+pillow to do that based on a csv from that histogram.

Ps: Using a somewhat older Nip2/Vips version.

**Comment by jcupitt** [comment]
Hello @MvGulik, 

You can use `hist_plot` to draw an image from a histogram, eg.:

![image](https://github.com/libvips/nip2/assets/580843/15cdae8d-7d21-4387-8d52-c26b89a23316)

`hist_norm` will normalise a histogram, ie. make it "square".

You can also export a plot -- in a Plot window (B2 above), click File / Export Plot and you can save the nice plotted graph as a PNG.

**Comment by MvGulik** [comment]
Hi

Aha ... Got it converted. Thanks.
Sorry. Have not looked in the Toolkits browser for a really long time.


> "_You can also export a plot -- in a Plot window (B2 above) ..._ "

That looks really nice. (_Unfortunately that plot-image was not available in the older version I'm using_.)
