### ISSUE TITLE
Nip2 Documentation

### ISSUE THREAD

**Issue by jpadfield** [libvips/nip2#73]
Hi, I was just wondering if the Nip2 documentation is hosted here in GitHub? I wanted to direct someone to  more information about using Nip2 and I am not sure what the best link is at the moment?
Thanks
Joe

**Comment by jcupitt** [comment]
Hi Joe, no, there's no on line copy right now, perhaps there should be. You can press F1 in the program to see a copy of the docs, of course.

**Comment by jpadfield** [comment]
Hi John, Ok, the F1 things works well, thanks. Do all of the old Mediawiki pages still exist? Would it be worth porting any over here to github, or is it all a little out of date now?

**Comment by jcupitt** [comment]
Yes, I copied all of the mediawiki pages over:

https://github.com/jcupitt/libvips/wiki

But I've only updated a few of them, and they may have broken image links.
