### ISSUE TITLE
Is it possible to create DeepZoom images from nip2?  (Possible feature request)

### ISSUE THREAD

**Issue by erdmann** [libvips/nip2#80]
Hi John,

Is it possible to create a DeepZoom image directly from within nip2?

Some things I tried:

- looking for a suitable file type from the "Save As" dialog;
- using a ".dz" extension.  In vips, rather than calling dzsave directly, I typically just give a fake ".dz" extension as a destination file, so I also tried manually entering a .dz extension in the "Save As" dialog, but nip2 gives an error like `Error writing image to file "/some/path/image.dz".
VipsFormat: "/some/path/image.dz" is not a supported image format`;
- looking for an `im_dzsave` function or similar.

Do you have any suggestions?  For example, is it possible to make a system call from within nip2 to run vips or other executables directly?

If it's not currently possible, I think this would be a very useful addition.  Here at the Rijksmuseum, nip2 is poised to become a much more major component of our image processing infrastructure, and the ability to create .dzi files directly without needing to drop into a terminal to run vips directly for this step would increase its accessibility.

Many thanks in advance!

**Comment by jcupitt** [comment]
Hi @erdmann,

Not directly, but you can call dzsave from a macro. Try typing:

```
vips_call "dzsave" [A1.value, "fred"] []
```

And it should save image `A1`. You could make a menu item for it, including all the save options.

Really, nip2 needs updating. I've been working on vips8, but I should switch to fixing up nip2 soon.

**Comment by erdmann** [comment]
Aha.  I had missed the `vips_call` function; I should've poked around in the .def files more thoroughly.  This does the job perfectly.

Many thanks again!

**Comment by jcupitt** [comment]
Yes, it lets you call any vips8 operation. You can give optional args like this:

```
vips_call "dzsave" [A1.value, "fred"] [
    $overlap => 2,
    $tile_size => 512
]
```

it's probably obvious.

**Comment by erdmann** [comment]
Thanks!

I have often wondered whether there was a way to have a cell as a conceptual sink in the data flow graph as a counterpart to cells which serve as sources by loading images from disk, and this serves exactly that purpose.
  
I also see that it's possible to set options for saving using the square bracket shorthand syntax:

``vips_call "vipssave" [A1.value, "foo.dz[overlap=2]"] []``


This opens up many possibilities.  Is there a canonical way to make a cell depend on another one in order to control the sequencing of operations?  For example, suppose in cell A2 one had a `vips_call "system" ...` that would process the image in cell A1 outside of nip2, with the effect that the outside program would write its results to file.  Then, in cell A3, the results would be read from disk back into nip2.  Cell A3 should only be attempted after A2 has run, and should be triggered to run again every time A2 is run.  If I understand correctly, this will automatically happen as long as nip2 detects that A3 depends on A2.

**Comment by jcupitt** [comment]
Yes, just make cells refer to each other and it should all work. The "magick" menu works like this (it uses `system` to run the commands).

**Comment by jcupitt** [comment]
@erdmann sorry to ping you on such an old issue, but I don't seem to have an email address.

nip4 has just had its first public test release:

https://github.com/jcupitt/nip4/releases

This is a rewrite of the GUI for the gtk4 UI toolkit, so it's quite a bit faster and more modern-looking. The backend is all the same, so it'll load all old workspaces.

I've not reimplemented the whole GUI (I never used quite large parts of it), so I'd love any feedback on what still needs adding, if you're still using this stuff.

I'll try to write a "nip4 for nip2 users" post running over the big differences, though it should be pretty obvious.

**Comment by erdmann** [comment]
Fantastic!  I still use nip2 daily and will be teaching it to students in Paris and Amsterdam.  I'll give the new one a spin and provide feedback.  I'll email you shortly with my current address, too.  Thanks!

**Comment by jcupitt** [comment]
That's great! 

Major changes:

- much better image view window knows about image pyramids, does smooth zooming on your GPU, knows about alpha, animation and multipage images, and should be a lot quicker
- much better animated column drag
- much better animated row drag, and you can drag rows between columns
- left-drag on background to pan around (works in workspaces and in image windows)
- mousewheel to zoom
- new "toolkits" thing down the left includes search (press the magnifying glass) and stays open, so you can use many items from the same menu quickly
- no preferences system (it should all be automatic)
- a single and very simple burger menu at the top right, other actions are all in context menus on tabs, workspace background, rows, columns
- uses native file dialogs
- you can copy-paste in image windows (!!!!) try "print screen" then ^V into an image window, you can also ^C then ^V into mspaint etc. (this feature needs win11, or you can use win + s in win10, should work fine in linux)
- right click on background, then "Edit toolkits" for the programming window
- proper fullscreen support

Still missing:

- paintbox
- quite a few dialogs (I'm hoping people will edit cells instead)

Bugs:

- there are a few strange performance black holes I've not yet found fixes for
- see https://github.com/jcupitt/nip4/blob/main/TODO for lots of opther things

macOS build coming soon.

**Comment by erdmann** [comment]
Very cool!

My two main use cases are (1) running remotely on a linux workstation and displaying locally via x2goclient, and (2) running locally on macOS.  For the conservation students I teach at the University of Amsterdam, easy installation is important so the macOS installer will be most welcome.

I tried an old email address I have for you at Imperial College, but it bounced.  My (publicly findable) academic address is r.g.erdmann@uva.nl.

**Comment by jcupitt** [comment]
Great! I'm jcupitt@gmail.com

The macos "installer" will just be a homebrew formula, so they'd need to enter a few shell commands. A proper.pkg would be quite a bit more work :( 

The new GUI is all rendered on the GPU at 60fps, so I don't know how well it'll work over x11.
