### ISSUE TITLE
Showing plots - libgoffice

### ISSUE THREAD

**Issue by jpadfield** [libvips/nip2#82]
I have nip2 installed from the code included in Ubuntu 19.04 and it does not let me view plots within nip2. Is it possible to do this and if so what additional optional packages need to be installed?

In an attempt to solve this I have tried to build nip2 from source and the configure output indicates that I do not have libgoffice or libgvc installed.

However, I have just check and both of these do seem to be installed on my machine so I am not sure what to try next. Are the versions of these in Ubuntu 19.04 to new, or are the following simply the wrong packages?

- libgvc6 (ver 2.40.1-6)
- libgoffice-0.10-dev (ver 0.10.44-1)

Thanks

**Comment by jcupitt** [comment]
Hi Joe, you need libgoffice-0.8. That was the final version which worked with gtk+2. You'll need to build it yourself, unfortunately. 

You can probably ignore libgvc.

**Comment by jpadfield** [comment]
That sounds vaguely familiar to me now, so sorry if you have told me that before :-)
