### ISSUE TITLE
Documentation Bug: mkset takes two arguments

### ISSUE THREAD

**Issue by mhirsch** [libvips/nip2#84]
[Here](https://github.com/libvips/nip2/blob/d81f3c8ffef1c191d50855218a179ea784403766/doc/src/program.tex#L824) in this docs, `mkset` is defined as `mkset l`.
However, [here](https://github.com/libvips/nip2/blob/d81f3c8ffef1c191d50855218a179ea784403766/share/nip2/start/_list.def#L288) `mkset` is defined as `mkset eq l`, where it takes a comparison equation. `mkset` does not work in nip2 without the equation argument.

**Comment by jcupitt** [comment]
Fixed! Thank you very much Matt.
