### ISSUE TITLE
Failure to open gif files

### ISSUE THREAD

**Issue by lxs602** [libvips/nip2#94]
Hi,

I do not seem to be able to open any gif files with Nip2, which gives the error:

```
Load failed.

Unable to execute:
   Matrix_file "$HOME/Downloads/divider_uncropped.gif"
```

Am I doing anything wrong?

I am using Ubuntu 20.04:
libvips2:    8.9.1-2 
nip2:        8.7.0-1 

Thanks,
L

**Comment by jcupitt** [comment]
Hi @lxs602,

Sorry, GIF load is a libvips 8 feature, and nip2 is still using the libvips 7 API.

I have a nip3 update in a branch, but it's not finished. I need to find a few weeks to hack on it :(

**Comment by lxs602** [comment]
Ah. No worries. Thanks.
