### ISSUE TITLE
Nip2 is deleting source file on close

### ISSUE THREAD

**Issue by BillTheGoat** [libvips/nip2#97]
I am using Nip2-8.2 on Ubuntu. When I open a file, then make a selection of an area, then close the file, selecting "close without saving changes", the source file is deleted from the computer. Obviously not the expected behavior.

Thanks

**Comment by jcupitt** [comment]
Hello, I hope you didn't lose any work :( 

This was a very unfortunate bug that was fixed more than five years ago. I would update to a more recent version.

**Comment by BillTheGoat** [comment]
Just when you thought you could trust apt repositories... Thank you!
