### ISSUE TITLE
Would 'Appimage' be an options for distributing linux versions of Nip2 (or Nip3).

### ISSUE THREAD

**Issue by MvGulik** [libvips/nip2#98]
Not a fan of Snap or Flatpak (as such I kinda committed to not using those)

After getting to know about Appimage, I think this is way less invasive alternative for Linux users.
(Don't know anything about the distribution side of Appimage's though)

Any chance Nip2 could be using Appimage for its Linux version in the future ?

https://appimage.org/
https://appimage.github.io/apps/

**Comment by MvGulik** [comment]
No reaction for more than a year ... so I guess Appimage support is not going to happen ... so closing.

**Comment by jcupitt** [comment]
Hi, sorry for not replying.

I'm planning to use flatpak for nip4, you can try the image viewer component here:

https://flathub.org/apps/org.libvips.vipsdisp

Performance seems fine to me, and it integrates well with the rest of the desktop. I'm not sure what appimage would add.

**Comment by MvGulik** [comment]
... Unsubscribed after closing, and did not look back ...
(_low general linux motivation on my part, and its not getting better_.)

Have no substantial compelling arguments.

The future will tell how linux growing dependency on a few (_or eventually potentially one_) centralized parties to provide easy installable and up-to-date software for _normal users_ will work out.

Anyway ... Thought I found a potential nice alternative in distrobox ... but that already failed at the first podman step (_guess LTS is just one other overrated linux thing_) ... O well, as normal user I probably would not be able to use distrobox anyway.

**Comment by jcupitt** [comment]
nip4 is coming along (screenshot if you scroll down):

https://github.com/jcupitt/nip4

I'm hoping to have this done by the summer. Like vipsdisp, there will be a flatpak build and a native windows binary.

nip2 is more than 20 years old and was becoming tricky to build since many of the supporting libraries had dropped out of maintenance. Hopefully nip4 will be a lot easier (and prettier).
